### PR TITLE
Finished tests

### PR DESCRIPTION
**Pull request by Ilyes512**
I was looking at config libraries when I was looking through the source code and tests of this library. I noticed some t.Skip()'s so as an exercise I tried to implement them.

Why let something go to waste... :)

### CODE REVIEW

**Comment by joshbetz** [comment]
Thanks @Ilyes512! I've fixed the issue that is causing tests to fail in https://github.com/joshbetz/config/pull/4. Can you rebase against the master branch to pull those changes in here?

The code looks good. After looking at this again, `should successfully cast bool to float` seems awkward. Having a boolean in a JSON config and pulling out a `1.0` or `0.0` may not be ideal. Maybe we should drop support for bool to float specifically?

👍 otherwise though.

**Comment by Ilyes512** [comment]
> Can you rebase against the master branch to pull those changes in here?

Done.

> After looking at this again, should successfully cast bool to float seems awkward. 

Yeah, seems strange. Shall I remove it?

**Comment by joshbetz** [comment]
> Yeah, seems strange. Shall I remove it?

Yeah, let's remove it. Thanks!

**Comment by Ilyes512** [comment]
Done

**Pull request merged**
